<?php

namespace Padrao\Models\CadConsultaAnual\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class CadConsultaAnualResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'uuid'                  => $this->uuid,
            'uuid_aluno'            => $this->aluno->uuid,
            'dsc_consulta'          => $this->dsc_consulta,
            'cardiopatia'           => $this->cardiopatia,
            'pressao_arterial'      => $this->pressao_arterial,
            'diabete'               => $this->diabete,
            'glicemia'              => $this->glicemia,
            'colesterol'            => $this->colesterol,
            'triglicerideos'        => $this->triglicerideos,
            'obesidade'             => $this->obesidade,
            'problema_vascular'     => $this->problema_vascular,
            'tireoide'              => $this->tireoide,
            'osteoporose'           => $this->osteoporose,
            'cancer'                => $this->cancer,
            'asma_bronquite'        => $this->asma_bronquite,
            'alergia'               => $this->alergia,
            'cirurgias'             => $this->cirurgias,
            'fraturas'              => $this->fraturas,
            'entorse_luxacao'       => $this->entorse_luxacao,
            'dor_cabeca'            => $this->dor_cabeca,
            'anemia'                => $this->anemia,
            'gastrite_refluxo'      => $this->gastrite_refluxo,
            'desmaio'               => $this->desmaio,
            'convulsao'             => $this->convulsao,
            'tabagismo'             => $this->tabagismo,
            'outras_patologias'     => $this->outras_patologias,
            'medicamento_em_uso'    => $this->medicamento_em_uso,
            'dor_desconforto_peito' => $this->dor_desconforto_peito,
            'falta_ar_esforco_leve' => $this->falta_ar_esforco_leve,
            'falta_ar_repouso'      => $this->falta_ar_repouso,
            'tontura'               => $this->tontura,
            'palpitacoes'           => $this->palpitacoes,
            'cansaco_avds'          => $this->cansaco_avds,
            'dor_caminhar'          => $this->dor_caminhar,
            'apneia_ronco'          => $this->apneia_ronco,
            'classifica_sono'       => $this->classifica_sono,
            'localizacao'           => $this->localizacao,
            'intensidade'           => $this->intensidade,
            'tipo_dor'              => $this->tipo_dor,
            'frequencia_dor'        => $this->frequencia_dor,
            'tempo_dor'             => $this->tempo_dor,
            'tratamento'            => $this->tratamento,
            'quando_piora'          => $this->quando_piora,
            'quando_melhora'        => $this->quando_melhora,
            'obs_dor'               => $this->obs_dor,
            'nutricionista'         => $this->nutricionista,
            'cafe_manha'            => $this->cafe_manha,
            'lanche_manha'          => $this->lanche_manha,
            'almoco'                => $this->almoco,
            'lanche_tarde'          => $this->lanche_tarde,
            'jantar'                => $this->jantar,
            'lanche_noite'          => $this->lanche_noite,
            'agua_quantidade'       => $this->agua_quantidade,
            'bebida_alcool'         => $this->bebida_alcool,
            'suple_vita'            => $this->suple_vita,
            'obs_nutricional'       => $this->obs_nutricional,
            'exer_praticou'         => $this->exer_praticou,
            'exer_atuais'           => $this->exer_atuais,
            'parado_tempo'          => $this->parado_tempo,
            'obs_exer'              => $this->obs_exer,
            'lab_postura'           => $this->lab_postura,
            'lab_caract'            => $this->lab_caract,
            'obs_lab'               => $this->obs_lab,
            'per_peso'              => $this->per_peso,
            'per_quant'             => $this->per_quant,
            'obs_per'               => $this->obs_per,
            'obj_quais'             => $this->obj_quais,
            'obs_objetivo'          => $this->obs_objetivo,
            'met_quais'             => $this->met_quais,
            'obs_metas'             => $this->obs_metas
        ];
    }
}
